/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MeusIngressosRouteImport } from './routes/meus-ingressos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosSlugRouteImport } from './routes/jogos.$slug'
import { Route as ComprarSlugRouteImport } from './routes/comprar.$slug'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as ApiPixRouteImport } from './routes/api.pix'
import { Route as ApiWebhookMasterRouteImport } from './routes/api.webhook.master'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusIngressosRoute = MeusIngressosRouteImport.update({
  id: '/meus-ingressos',
  path: '/meus-ingressos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosSlugRoute = JogosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JogosRoute,
} as any)
const ComprarSlugRoute = ComprarSlugRouteImport.update({
  id: '/comprar/$slug',
  path: '/comprar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPixRoute = ApiPixRouteImport.update({
  id: '/api/pix',
  path: '/api/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookMasterRoute = ApiWebhookMasterRouteImport.update({
  id: '/api/webhook/master',
  path: '/api/webhook/master',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/jogos': typeof JogosRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-ingressos': typeof MeusIngressosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/pix': typeof ApiPixRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/comprar/$slug': typeof ComprarSlugRoute
  '/jogos/$slug': typeof JogosSlugRoute
  '/api/webhook/master': typeof ApiWebhookMasterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/jogos': typeof JogosRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-ingressos': typeof MeusIngressosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/pix': typeof ApiPixRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/comprar/$slug': typeof ComprarSlugRoute
  '/jogos/$slug': typeof JogosSlugRoute
  '/api/webhook/master': typeof ApiWebhookMasterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/jogos': typeof JogosRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-ingressos': typeof MeusIngressosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/pix': typeof ApiPixRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/comprar/$slug': typeof ComprarSlugRoute
  '/jogos/$slug': typeof JogosSlugRoute
  '/api/webhook/master': typeof ApiWebhookMasterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/jogos'
    | '/login'
    | '/meus-ingressos'
    | '/privacidade'
    | '/termos'
    | '/api/pix'
    | '/checkout/$orderId'
    | '/comprar/$slug'
    | '/jogos/$slug'
    | '/api/webhook/master'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/jogos'
    | '/login'
    | '/meus-ingressos'
    | '/privacidade'
    | '/termos'
    | '/api/pix'
    | '/checkout/$orderId'
    | '/comprar/$slug'
    | '/jogos/$slug'
    | '/api/webhook/master'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/jogos'
    | '/login'
    | '/meus-ingressos'
    | '/privacidade'
    | '/termos'
    | '/api/pix'
    | '/checkout/$orderId'
    | '/comprar/$slug'
    | '/jogos/$slug'
    | '/api/webhook/master'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  CadastroRoute: typeof CadastroRoute
  JogosRoute: typeof JogosRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeusIngressosRoute: typeof MeusIngressosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiPixRoute: typeof ApiPixRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  ComprarSlugRoute: typeof ComprarSlugRoute
  ApiWebhookMasterRoute: typeof ApiWebhookMasterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-ingressos': {
      id: '/meus-ingressos'
      path: '/meus-ingressos'
      fullPath: '/meus-ingressos'
      preLoaderRoute: typeof MeusIngressosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/$slug': {
      id: '/jogos/$slug'
      path: '/$slug'
      fullPath: '/jogos/$slug'
      preLoaderRoute: typeof JogosSlugRouteImport
      parentRoute: typeof JogosRoute
    }
    '/comprar/$slug': {
      id: '/comprar/$slug'
      path: '/comprar/$slug'
      fullPath: '/comprar/$slug'
      preLoaderRoute: typeof ComprarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pix': {
      id: '/api/pix'
      path: '/api/pix'
      fullPath: '/api/pix'
      preLoaderRoute: typeof ApiPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/master': {
      id: '/api/webhook/master'
      path: '/api/webhook/master'
      fullPath: '/api/webhook/master'
      preLoaderRoute: typeof ApiWebhookMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JogosRouteChildren {
  JogosSlugRoute: typeof JogosSlugRoute
}

const JogosRouteChildren: JogosRouteChildren = {
  JogosSlugRoute: JogosSlugRoute,
}

const JogosRouteWithChildren = JogosRoute._addFileChildren(JogosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  CadastroRoute: CadastroRoute,
  JogosRoute: JogosRouteWithChildren,
  LoginRoute: LoginRoute,
  MeusIngressosRoute: MeusIngressosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiPixRoute: ApiPixRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  ComprarSlugRoute: ComprarSlugRoute,
  ApiWebhookMasterRoute: ApiWebhookMasterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
